server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone:
        http://discovery-service:8761/eureka
springdoc:
  packages-to-scan: dev.n7meless.economyservice
parse:
  dotabuff:
    url: https://www.dotabuff.com/heroes/
