server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
springdoc:
  packages-to-scan: dev.n7meless.impactservice
parse:
  dotabuff:
    url: https://www.dotabuff.com/heroes/