server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone:
        http://discovery-service:8761/eureka
caching:
  spring:
    lanesTTL: 10000000
springdoc:
  packages-to-scan: dev.n7meless.laneservice
parse:
  dotabuff:
    url: https://www.dotabuff.com/heroes/