version: "3.7"
services:
  config-service:
    image: n7meless/config-service:1.0-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/counter/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
  discovery-service:
    image: n7meless/discovery-service:1.0-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8761/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
  counter-service:
    image: n7meless/counter-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  economy-service:
    image: n7meless/economy-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - counter-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  farm-service:
    image: n7meless/farm-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - counter-service
      - economy-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  hero-service:
    image: n7meless/hero-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - counter-service
      - economy-service
      - farm-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  impact-service:
    image: n7meless/impact-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - counter-service
      - economy-service
      - farm-service
      - hero-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  lane-service:
    image: n7meless/lane-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - counter-service
      - economy-service
      - farm-service
      - hero-service
      - impact-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    image: n7meless/gateway-service:1.0-SNAPSHOT
    ports:
      - "8888:8888"
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config-service
      - discovery-service
      - counter-service
      - economy-service
      - farm-service
      - hero-service
      - impact-service
      - lane-service