logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          route:
            RouteDefinitionLocator: info
          gateway:
            trace
springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: api-gateway
      packages-to-scan:
        - dev.n7meless.apigateway
        - dev.n7meless.economyservice
      display-name: API Gateway
    - group: hero-service
      paths-to-match:
        - /api/hero
        - /api/counter
        - /api/economy
      display-name: Hero Service
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - name: counter-service
        url: /api/counter
      - name: hero-service
        url: /api/hero
      - name: economy-service
        url: /api/economy
    path: /swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices
  cloud:
    gateway:
      routes:
        - id: economy-service
          uri: lb://economy-service
          predicates:
            - Path=/api/economy
        - id: farm-service
          uri: lb://farm-service
          predicates:
            - Path=/api/farm
        - id: impact-service
          uri: lb://impact-service
          predicates:
            - Path=/api/impact
        - id: lanes-service
          uri: lb://lanes-service
          predicates:
            - Path=/api/lane
        - id: counter-service
          uri: lb://counter-service
          predicates:
            - Path=/api/counter
        - id: hero-service
          uri: lb://hero-service
          predicates:
            - Path=/api/hero
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**