spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: n7meless
      port: 27017
      host: localhost
  application:
    name: hero-service

api:
  opendota:
    url: https://api.opendota.com/api/

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone:
        http://user:password@localhost:8761/eureka


