server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone:
        http://user:password@localhost:8761/eureka
spring:
  application:
    name:
      lane-service
caching:
  spring:
    lanesTTL: 10000000
