server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone:
        http://user:password@localhost:8761/eureka
spring:
  application:
    name:
      impact-service
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    instances:
      invontory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

#Resilience4J Timeout Properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
#Resilience4J Retry Properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
