eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.default-zone=http://localhost:8761/eureka
server.port=8761
eureka.username=${EUREKA_USERNAME:user}
eureka.password=${EUREKA_PASSWORD:password}
